apiVersion: apps/v1
kind: Deployment
metadata:
  name: yj-msa-member-depl
  namespace: yjchoi-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yj-msa-member
  template:
    metadata:
      labels:
        app: yj-msa-member
    spec:
      containers:
      - name: yj-msa-member
        image: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com/yj-msa-member:latest
        ports:
        - containerPort: 8080 # 스프링에서 쓰는 포트번호
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: yj-app-secrets  # 노션에 만드는 명령어 있음.
              key: DB_HOST #명령어 통해서 사용할 것들임임
        - name: DB_PW #application.yml에서 찾는 지표
          valueFrom:
            secretKeyRef:
              name: yj-app-secrets
              key: DB_PW
        - name: AWS_KEY
          valueFrom:
            secretKeyRef:
              name: yj-app-secrets
              key: AWS_KEY
        - name: AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: yj-app-secrets
              key: AWS_SECRET
        # 컨테이너 상태 확인 (healthcheck)
        readinessProbe:
          httpGet:
            # healthcheck 경로
            path: /member/health
            port: 8080
          # 컨테이너 시작 후 지연
          initialDelaySeconds: 10
          # 확인 반복 주기
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: yj-msa-member-service
  namespace: yjchoi-ns
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: yj-msa-member
---