apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: yjchoi-ns
spec:
  replicas: 2
  selector:
  # replicaset이 관리할 pod가 무엇인가?
    matchLabels:
      app: my-nginx
  template:
    metadata:
    # pod에 대한 레플리카셋 라벨. 이게 서비스의 selector과 같음음
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: yjchoi-ns
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30083
  selector:
    app: my-nginx