name: deploy order order-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2
      
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
  
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name 2team-cluster --region ap-northeast-2  #클러스터명 최신화

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: member build and push docker image to ecr
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: yj-msa-member
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./5.msa/member/Dockerfile ./5.msa/member
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: eks kubectl apply
        run: |
          kubectl apply -f ./5.msa/member/k8s/depl_svc.yml
          kubectl rollout restart deployment yj-msa-member-depl -n yjchoi-ns 



      - name: ordering build and push docker image to ecr
        env:
            REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
            REPOSITORY: yj-msa-order
            IMAGE_TAG: latest
        run: |
            docker build \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f ./5.msa/ordering/Dockerfile ./5.msa/ordering
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  
      - name: eks kubectl apply
        run: |
            kubectl apply -f ./5.msa/ordering/k8s/depl_svc.yml
            kubectl rollout restart deployment yj-msa-ordering-depl -n yjchoi-ns 



      - name: product build and push docker image to ecr
        env:
              REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
              REPOSITORY: yj-msa-product
              IMAGE_TAG: latest
        run: |
              docker build \
              -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
              -f ./5.msa/product/Dockerfile ./5.msa/product
              docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    
      - name: eks kubectl apply
        run: |
              kubectl apply -f ./5.msa/product/k8s/depl_svc.yml
              kubectl rollout restart deployment yj-msa-product-depl -n yjchoi-ns 